"""
dag_generator.py — Stage 5
Generates production-style Airflow DAG, YAML config, and Databricks notebook
Matches real Peacock/NBCU pattern:
  → DatabricksSubmitRunOperator
  → SlackWebhookOperator for alerts
  → YAML config per environment (dev/stage/prod)
  → Databricks PySpark notebook
"""

import os


# ─────────────────────────────────────────
# MAIN ENTRY POINT — called by tools.py
# ─────────────────────────────────────────
def generate_pipeline(
    pipeline_name: str,       # "top_subscribers"
    schedule_interval: str,   # "0 7 * * *"
    sql: str,                 # actual SQL query
    input_tables: list,       # ["subscribers", "watch_history"]
    output_table: str,        # "top_subscribers_daily"
    description: str          # "Daily top subscribers by watch time"
) -> str:
    """
    Generates all 3 pipeline files and saves them to output folder.
    Returns summary of what was created.
    """
    output_dir = "output"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Clean pipeline name for file naming
    # "top subscribers" → "top_subscribers"
    clean_name = pipeline_name.lower().replace(" ", "_")

    # Generate all 3 files
    dag_content      = generate_dag(clean_name, schedule_interval, description)
    config_content   = generate_config(clean_name, schedule_interval, input_tables, output_table)
    notebook_content = generate_notebook(clean_name, sql, input_tables, output_table)

    # Save all 3 files
    dag_file      = os.path.join(output_dir, f"{clean_name}_dag.py")
    config_file   = os.path.join(output_dir, f"{clean_name}_config.yml")
    notebook_file = os.path.join(output_dir, f"{clean_name}_notebook.py")

    with open(dag_file, "w") as f:
        f.write(dag_content)

    with open(config_file, "w") as f:
        f.write(config_content)

    with open(notebook_file, "w") as f:
        f.write(notebook_content)

    return f"""Pipeline generated successfully!

Files saved to output/:
  → {clean_name}_dag.py        (Airflow DAG)
  → {clean_name}_config.yml    (Environment configs: dev/stage/prod)
  → {clean_name}_notebook.py   (Databricks PySpark notebook)

Pipeline: {description}
Schedule: {schedule_interval}
Input tables: {', '.join(input_tables)}
Output table: {output_table}"""


# ─────────────────────────────────────────
# 1. AIRFLOW DAG GENERATOR
# ─────────────────────────────────────────
def generate_dag(
    pipeline_name: str,
    schedule_interval: str,
    description: str
) -> str:
    """Generates Airflow DAG file matching Peacock pattern."""

    return f'''"""
{pipeline_name}_dag.py
Generated by DE Copilot
{description}
"""

import json
import yaml
from datetime import datetime, timedelta

from airflow import DAG
from airflow.models import Variable
from airflow.hooks.base_hook import BaseHook
from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
from airflow.providers.slack.operators.slack_webhook import SlackWebhookOperator

# ── Environment config ──
MOUNT_POINT = Variable.get("MOUNT_POINT", default_var="/mnt/airflow-dags")
ENVIRONMENT  = Variable.get("ENVIRONMENT", default_var="dev")

sql_metadata = yaml.load(
    open(f"{{MOUNT_POINT}}/config/{pipeline_name}_config.yml").read(),
    Loader=yaml.FullLoader
)[ENVIRONMENT]

SLACK_CONN_ID = "{{DAG[SLACK_CONN_ID]}}".format(**sql_metadata)


# ── Slack alert functions ──
def task_fail_slack_alert(context):
    slack_webhook_token = BaseHook.get_connection(SLACK_CONN_ID).password
    slack_msg = """
        :red_circle: Task Failed.
        *Task*: {{task}}
        *Dag*: {{dag}}
        *Execution Time*: {{exec_date}}
        *Log Url*: {{log_url}}
    """.format(
        task=context.get("task_instance").task_id,
        dag=context.get("task_instance").dag_id,
        exec_date=context.get("execution_date"),
        log_url=context.get("task_instance").log_url,
    )
    failed_alert = SlackWebhookOperator(
        task_id="slack_alert",
        slack_webhook_conn_id=SLACK_CONN_ID,
        channel="#airflow-alerts-prod",
        message=slack_msg,
        username="airflow"
    )
    return failed_alert.execute(context=context)


def task_retry_slack_alert(context):
    slack_webhook_token = BaseHook.get_connection(SLACK_CONN_ID).password
    slack_msg = """
        :yellow_circle: Task in retry.
        *Task*: {{task}}
        *Dag*: {{dag}}
        *Error*: {{exception}}
        *Execution Time*: {{exec_date}}
    """.format(
        task=context.get("task_instance").task_id,
        dag=context.get("task_instance").dag_id,
        exception=str(context.get("exception"))[:700],
        exec_date=context.get("execution_date"),
    )
    failed_alert = SlackWebhookOperator(
        task_id="slack_retry_alert",
        slack_webhook_conn_id=SLACK_CONN_ID,
        channel="#airflow-alerts-prod",
        message=slack_msg,
        username="airflow"
    )
    return failed_alert.execute(context=context)


# ── Default args ──
default_args = {{
    "owner": "de_team",
    "depends_on_past": False,
    "email": ["de_alerts@peacock.com"],
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": int("{{DAG[RETRIES]}}".format(**sql_metadata)),
    "retry_delay": timedelta(minutes=int("{{DAG[RETRY_DELAY]}}".format(**sql_metadata))),
    "on_failure_callback": task_fail_slack_alert,
    "on_retry_callback": task_retry_slack_alert,
}}


# ── DAG definition ──
dag = DAG(
    dag_id="{pipeline_name}_daily",
    start_date=datetime(2026, 1, 1),
    default_args=default_args,
    catchup=False,
    description="{description}",
    schedule_interval="{{DAG[SCHEDULE_INTERVAL]}}".format(**sql_metadata),
    tags=["de_copilot", "peacock"],
    access_control={{
        "DE_Engineer": {{"can_edit", "can_read"}}
    }}
)

# ── Load Databricks config ──
cluster_metadata = yaml.load(
    open(f"{{MOUNT_POINT}}/config/clusterconfigs.yml").read(),
    Loader=yaml.FullLoader
)

databricks_metadata = {{
    "RUN_DATE": "{{{{ execution_date.in_timezone(\\'UTC\\').strftime(\\\'%Y-%m-%d\\\') }}}}",
}}
databricks_metadata.update(sql_metadata)
param_json = json.dumps(databricks_metadata)


# ── Tasks ──
run_{pipeline_name} = DatabricksSubmitRunOperator(
    task_id="run_{pipeline_name}",
    databricks_conn_id="{{DAG[DATABRICKS_CONN_ID]}}".format(**sql_metadata),
    json={{
        "run_name": "{pipeline_name}_{{{{ ts }}}}",
        "timeout_seconds": int("{{DAG[TIMEOUT_SECONDS]}}".format(**sql_metadata)),
        "new_cluster": cluster_metadata.get("run_{pipeline_name}", {{}}).get("cluster", {{}}),
        "spark_python_task": {{
            "python_file": f"dbfs:{{MOUNT_POINT}}/sql/{pipeline_name}_notebook.py",
            "parameters": [param_json]
        }},
        "access_control_list": cluster_metadata.get("access_control_list", []),
    }},
    deferrable=True,
    polling_period_seconds=90,
    pool="de_databricks_pool",
    depends_on_past=False,
    dag=dag
)
'''


# ─────────────────────────────────────────
# 2. YAML CONFIG GENERATOR
# ─────────────────────────────────────────
def generate_config(
    pipeline_name: str,
    schedule_interval: str,
    input_tables: list,
    output_table: str
) -> str:
    """Generates YAML config with dev/stage/prod environments."""

    input_tables_yaml = "\n".join([f"    - {t}" for t in input_tables])

    return f"""# {pipeline_name}_config.yml
# Generated by DE Copilot
# Environment-specific config for {pipeline_name} pipeline

dev:
  DAG:
    SCHEDULE_INTERVAL: "{schedule_interval}"
    RETRIES: "2"
    RETRY_DELAY: "5"
    TIMEOUT_SECONDS: "3600"
    CATCHUP: "False"
    DATABRICKS_CONN_ID: "databricks_dev"
    SLACK_CONN_ID: "slack_dev"
  NOTEBOOK_PATH: "/de_copilot/{pipeline_name}_notebook"
  INPUT_TABLES:
{input_tables_yaml}
  OUTPUT_TABLE: "dev.{output_table}"
  SILVER_SCHEMA: "dev_silver"

stage:
  DAG:
    SCHEDULE_INTERVAL: "{schedule_interval}"
    RETRIES: "2"
    RETRY_DELAY: "5"
    TIMEOUT_SECONDS: "3600"
    CATCHUP: "False"
    DATABRICKS_CONN_ID: "databricks_stage"
    SLACK_CONN_ID: "slack_stage"
  NOTEBOOK_PATH: "/de_copilot/{pipeline_name}_notebook"
  INPUT_TABLES:
{input_tables_yaml}
  OUTPUT_TABLE: "stage.{output_table}"
  SILVER_SCHEMA: "stage_silver"

prod:
  DAG:
    SCHEDULE_INTERVAL: "{schedule_interval}"
    RETRIES: "3"
    RETRY_DELAY: "5"
    TIMEOUT_SECONDS: "7200"
    CATCHUP: "False"
    DATABRICKS_CONN_ID: "databricks_prod"
    SLACK_CONN_ID: "slack_prod"
  NOTEBOOK_PATH: "/de_copilot/{pipeline_name}_notebook"
  INPUT_TABLES:
{input_tables_yaml}
  OUTPUT_TABLE: "prod.{output_table}"
  SILVER_SCHEMA: "prod_silver"
"""


# ─────────────────────────────────────────
# 3. DATABRICKS NOTEBOOK GENERATOR
# ─────────────────────────────────────────
def generate_notebook(
    pipeline_name: str,
    sql: str,
    input_tables: list,
    output_table: str
) -> str:
    """Generates Databricks PySpark notebook matching Peacock pattern."""

    input_tables_reads = "\n".join([
        f"""# Read {table}
df_{table} = spark.read.format("delta").table(f"{{SILVER['{ table.upper() }']}}")
df_{table}.createOrReplaceTempView("{table}")
print(f"Loaded {{SILVER['{table.upper()}']}}: {{df_{table}.count()}} rows")
"""
        for table in input_tables
    ])

    return f'''"""
{pipeline_name}_notebook.py
Generated by DE Copilot
Databricks PySpark notebook for {pipeline_name} pipeline
"""

import json
import sys
import yaml
from datetime import datetime

# ── Spark config (Peacock standard settings) ──
spark.conf.set("spark.sql.shuffle.partitions", "auto")
spark.conf.set("spark.databricks.adaptive.autoOptimizeShuffle.preshufflePartitionSizeInBytes", 67108864)
spark.conf.set("spark.sql.adaptive.skewJoin.enabled", "true")
spark.conf.set("spark.databricks.adaptive.autoBroadcastJoinThreshold", 500 * 1024 * 1024)

# ── Load parameters from Airflow ──
params = json.loads(sys.argv[1])
for param_key, param_value in params.items():
    globals()[param_key] = param_value

RUN_DATE = params.get("RUN_DATE", datetime.now().strftime("%Y-%m-%d"))
print(f"Run date: {{RUN_DATE}}")

# ── Load YAML config ──
lines = spark.read.text(yml_filepath).collect()
config_dict = {{}}
current_key = None
for line in lines:
    line_value = line["value"]
    if line_value.strip() and not line_value.strip().startswith("#"):
        if line_value.strip().endswith(":"):
            current_key = line_value.strip()[:-1]
            config_dict[current_key] = {{}}
        else:
            key, value = line_value.strip().split(":", 1)
            config_dict[current_key][key.strip()] = yaml.safe_load(value.strip())

for param_key, param_value in config_dict.items():
    globals()[param_key] = param_value

# ── Read input tables ──
print(f"Loading input tables...")

{input_tables_reads}

# ── Delete existing data for run date ──
spark.sql(f"""
    DELETE FROM {{SILVER["{output_table.upper()}"]}}
    WHERE run_date = "{{RUN_DATE}}"
""")

# ── Run main SQL ──
print(f"Running {pipeline_name} query...")

df_final = spark.sql("""
{sql}
""")

df_final.createOrReplaceTempView("df_final")

# ── Write to Silver table ──
spark.sql(f"""
    INSERT INTO {{SILVER["{output_table.upper()}"]}}
    SELECT * FROM df_final
""")

df_final.write.format("delta") \\
    .mode("append") \\
    .partitionBy("run_date") \\
    .saveAsTable(f"{{SILVER['{output_table.upper()}']}}")

print(f"{{datetime.now()}} — {{SILVER['{output_table.upper()}']}} loaded successfully")

# ── Optimize table ──
print(f"Optimizing {{SILVER['{output_table.upper()}']}}...")
spark.sql(f"OPTIMIZE {{SILVER['{output_table.upper()}']}} WHERE run_date >= current_date()-1")
print(f"Optimization complete: {{datetime.now()}}")
'''
